export const CarouselData = () => {
    const carouselData = [
      {
        id: 1,
        title: 'New York',
        country: 'USA',
        description: 'The city that never sleeps, renowned for its iconic skyline, Broadway theaters, and diverse culture.',
        information: `New York City is a bustling metropolis offering iconic landmarks such as the Statue of Liberty, Empire State Building, and Central Park. It's a melting pot of cultures with neighborhoods like Chinatown, Harlem, and Williamsburg, each offering unique cuisines and experiences. Visitors can explore world-class museums like the Metropolitan Museum of Art and MoMA, catch a Broadway show in Times Square, and enjoy shopping in SoHo or Fifth Avenue. The city's dynamic arts scene, historical sites, and diverse food culture make it an unforgettable destination for all types of travelers.`,
        popularity: 'Extremely popular among tourists year-round, especially in spring and fall.',
        score: '9.5',
        bestTimeToVisit: 'April to June, September to early November',
        mustSeeAttractions: ['Statue of Liberty', 'Central Park', 'Times Square', 'Metropolitan Museum of Art'],
        localTips: 'Buy tickets in advance for Broadway shows and visit museums on free-entry days.',
        coordinates: { lat: 40.7128, lng: -74.006 },
        image: 'https://images.unsplash.com/photo-1483653364400-eedcfb9f1f88?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      },
      {
        id: 2,
        title: 'London',
        country: 'UK',
        description: 'A historic metropolis featuring landmarks like Big Ben, the London Eye, and a rich cultural heritage.',
        information: `London seamlessly blends centuries of history with modern sophistication. Explore the Tower of London and Buckingham Palace, walk along the River Thames, or ride the iconic London Eye for stunning city views. The city offers world-class theaters in the West End, diverse markets like Borough Market, and famous museums including the British Museum and Tate Modern. London's neighborhoods, from the trendy Shoreditch to upscale Kensington, offer a wide variety of dining, shopping, and cultural experiences. Rich in royal history, cultural diversity, and vibrant nightlife, London is a destination that captivates all visitors.`,
        popularity: 'One of the most visited cities worldwide, with strong tourist flow year-round.',
        score: '9.2',
        bestTimeToVisit: 'March to May, September to November',
        mustSeeAttractions: ['Big Ben', 'Tower of London', 'Buckingham Palace', 'British Museum'],
        localTips: 'Use the Oyster card for convenient public transport and explore lesser-known neighborhoods like Camden.',
        coordinates: { lat: 51.5074, lng: -0.1278 },
        image: 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      },
      {
        id: 3,
        title: 'Tokyo',
        country: 'Japan',
        description: 'A vibrant blend of tradition and innovation, known for its bustling streets, cherry blossoms, and towering skyscrapers.',
        information: `Tokyo offers a unique blend of ultra-modern life and deep-rooted traditions. Wander through neon-lit districts like Shibuya and Shinjuku, explore historic temples such as Senso-ji, and experience the peaceful beauty of Ueno Park during cherry blossom season. Tokyo is also a food lover’s paradise, famous for sushi, ramen, and Michelin-starred restaurants. The city boasts efficient public transport, endless shopping districts, and vibrant pop culture. Tokyo balances the frenetic pace of a megacity with serene gardens and traditional tea ceremonies, making it a fascinating destination.`,
        popularity: 'Highly popular, especially during cherry blossom and autumn foliage seasons.',
        score: '9.4',
        bestTimeToVisit: 'March to May, October to November',
        mustSeeAttractions: ['Shibuya Crossing', 'Senso-ji Temple', 'Tokyo Tower', 'Ueno Park'],
        localTips: 'Buy a prepaid transportation card and try local street food in small alleyways.',
        coordinates: { lat: 35.6762, lng: 139.6503 },
        image: 'https://images.unsplash.com/photo-1513407030348-c983a97b98d8?q=80&w=2072&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      },
      {
        id: 4,
        title: 'Bangkok',
        country: 'Thailand',
        description: 'Thailand’s capital, famous for its ornate temples, vibrant street life, and bustling markets.',
        information: `Bangkok is a city of contrasts, where gilded temples like Wat Arun and Wat Pho sit alongside bustling street markets and modern skyscrapers. The vibrant street food scene offers everything from spicy pad thai to exotic fruits. Visitors can enjoy boat rides on the Chao Phraya River, shop in sprawling malls like MBK Center, and experience the nightlife on Khao San Road. Bangkok is also a gateway to Thailand's other attractions, offering easy access to beautiful beaches and cultural sites. The city’s energy and warm hospitality make it an unforgettable travel experience.`,
        popularity: 'Extremely popular among both backpackers and luxury travelers.',
        score: '8.8',
        bestTimeToVisit: 'November to February',
        mustSeeAttractions: ['Wat Arun', 'Wat Pho', 'Grand Palace', 'Chatuchak Market'],
        localTips: 'Avoid rush hour traffic by using the BTS Skytrain and try local street food stalls.',
        coordinates: { lat: 13.7563, lng: 100.5018 },
        image: 'https://images.unsplash.com/photo-1510379872535-9310dc6fd6a7?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      },
      {
        id: 5,
        title: 'Paris',
        country: 'France',
        description: 'The romantic capital of France, home to the Eiffel Tower, art museums, and charming cafés.',
        information: `Paris captivates with its timeless beauty, historic landmarks, and vibrant culture. Visit the iconic Eiffel Tower, stroll through the artistic Montmartre district, and admire masterpieces at the Louvre and Musée d'Orsay. The city is famous for its charming cafés, patisseries, and gourmet dining. Walk along the Seine River or relax in the Luxembourg Gardens. Paris is also renowned for fashion, shopping on the Champs-Élysées, and lively cultural events. Its romantic atmosphere and rich heritage make it a top choice for travelers worldwide.`,
        popularity: 'One of the world’s most visited cities, especially popular in spring and summer.',
        score: '9.6',
        bestTimeToVisit: 'April to June, September to October',
        mustSeeAttractions: ['Eiffel Tower', 'Louvre Museum', 'Notre-Dame Cathedral', 'Montmartre'],
        localTips: 'Buy museum passes for skip-the-line access and explore the city by walking or bike.',
        coordinates: { lat: 48.8566, lng: 2.3522 },
        image: 'https://plus.unsplash.com/premium_photo-1661919210043-fd847a58522d?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      },
      {
        id: 6,
        title: 'Milano',
        country: 'Italy',
        description: 'Italy’s fashion hub, boasting impressive architecture, world-class shopping, and rich history.',
        information: `Milan is Italy’s fashion capital and a city rich in history and culture. Marvel at the stunning Gothic Duomo di Milano, visit the famous opera house La Scala, and explore art at Pinacoteca di Brera. The city is known for its luxury shopping districts, including Via Montenapoleone, and vibrant aperitivo culture. Milan also hosts important fashion events and design fairs. Its blend of historic charm and modern style makes it a dynamic and sophisticated destination for travelers.`,
        popularity: 'Highly popular with fashion enthusiasts and cultural tourists.',
        score: '8.7',
        bestTimeToVisit: 'September to November, March to May',
        mustSeeAttractions: ['Duomo di Milano', 'La Scala', 'Galleria Vittorio Emanuele II', 'Sforza Castle'],
        localTips: 'Enjoy an aperitivo in the Navigli district and buy tickets in advance for La Scala opera.',
        coordinates: { lat: 45.4642, lng: 9.1900 },
        image: 'https://images.unsplash.com/photo-1513581166391-887a96ddeafd?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      },
      {
        id: 7,
        title: 'Barcelona',
        country: 'Spain',
        description: 'A Spanish city known for its unique architecture, beautiful beaches, and lively atmosphere.',
        information: `Barcelona enchants with its unique blend of Gothic and modernist architecture, vibrant street life, and Mediterranean beaches. Explore Gaudí’s masterpieces such as the Sagrada Família and Park Güell. Wander the charming narrow streets of the Gothic Quarter and enjoy tapas and seafood along La Rambla. Barcelona is famous for its festivals, nightlife, and cultural events, making it a dynamic city for visitors who want a mix of history, art, and relaxation by the sea.`,
        popularity: 'Very popular, especially in summer and during festivals.',
        score: '9.1',
        bestTimeToVisit: 'May to June, September to October',
        mustSeeAttractions: ['Sagrada Família', 'Park Güell', 'La Rambla', 'Gothic Quarter'],
        localTips: 'Book Gaudí attractions online early and watch out for pickpockets in crowded areas.',
        coordinates: { lat: 41.3851, lng: 2.1734 },
        image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      },
      {
        id: 8,
        title: 'Vienna',
        country: 'Austria',
        description: 'Austria’s capital, celebrated for its classical music heritage, historic buildings, and vibrant cultural scene.',
        information: `Vienna is a city steeped in imperial grandeur and classical music tradition. Visit the Schönbrunn Palace, the Hofburg, and the stunning St. Stephen’s Cathedral. The city hosts world-renowned orchestras and opera performances, reflecting its musical heritage. Enjoy Viennese coffeehouse culture, museums like the Belvedere, and beautiful parks. Vienna blends baroque architecture with modern urban life, offering a sophisticated cultural experience for visitors.`,
        popularity: 'Popular with lovers of classical music, art, and history.',
        score: '9.0',
        bestTimeToVisit: 'April to June, September to October',
        mustSeeAttractions: ['Schönbrunn Palace', 'St. Stephen’s Cathedral', 'Belvedere Museum', 'Vienna State Opera'],
        localTips: 'Visit coffeehouses early to avoid crowds and book concert tickets in advance.',
        coordinates: { lat: 48.2082, lng: 16.3738 },
        image: 'https://images.unsplash.com/photo-1516550893923-42d28e5677af?q=80&w=2072&auto=format&fit=crop&ixlib=rb-4'},
    ];
  
    return carouselData;
  };
  
  export default CarouselData;
  